name: Collect and Visualize Solar Data

# Trigger the workflow on pushes to the main branch and daily at midnight UTC
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # This is the default and allows pushing back to the repo

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the solar data collection script
      - name: Run collect_solar_data.py
        run: |
          python collect_solar_data.py

      # 5. Commit and push the generated solar data CSV
      - name: Commit solar data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add india_solar_data.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update solar data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. Run the visualization script
      - name: Run visualize_solar_data.py
        run: |
          python visualize_solar_data.py

      # 7. Commit and push the visualization outputs
      - name: Commit visualization files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add solar_potential_high_res.png india_solar_potential.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update solar visualization [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}