name: Run Raydium Solar Map Generation
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install GDAL dependencies first
      - name: Install GDAL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev python3-gdal

      # Get GDAL version and set environment variables
      - name: Set GDAL environment variables
        run: |
          export GDAL_VERSION=$(gdal-config --version)
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          echo "GDAL_VERSION=$GDAL_VERSION" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=$C_INCLUDE_PATH" >> $GITHUB_ENV

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache NASA POWER data
        uses: actions/cache@v3
        with:
          path: nasa_power_cache
          key: ${{ runner.os }}-nasa_power_cache-${{ hashFiles('**/raydium.py') }}
          restore-keys: |
            ${{ runner.os }}-nasa_power_cache-

      # Install dependencies in the correct order
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install GDAL==$(gdal-config --version)
          pip install fiona==1.9.4
          pip install -r requirements.txt

      - name: Verify 'india-soi.geojson' Presence
        run: |
          if [ -f india-soi.geojson ]; then
            echo "'india-soi.geojson' found."
          else
            echo "'india-soi.geojson' not found. Please ensure it exists in the repository root."
            exit 1
          fi

      - name: List Files Before Script Execution
        run: |
          echo "Listing files before running the script:"
          ls -la

      - name: Run Python Script
        run: |
          echo "Executing raydium.py..."
          python raydium.py

      - name: List Files After Script Execution
        run: |
          echo "Listing files after running the script:"
          ls -la

      - name: Display log file
        if: always()  # Changed to always() to see logs even if script fails
        run: |
          if [ -f "solar_map.log" ]; then
            echo "Displaying solar_map.log contents:"
            cat solar_map.log
          else
            echo "solar_map.log does not exist."
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Output Files
        run: |
          git add india_solar_potential.html india_solar_data.csv solar_potential_high_res.png solar_map.log || echo "No output files to add."

      - name: Commit Changes
        run: |
          git commit -m "Update solar map outputs via GitHub Actions" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}