name: Generate Solar Potential Data

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight (00:00 UTC)
  workflow_dispatch:      # Allow manual trigger

jobs:
  generate-data:
    name: Generate Solar Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations

      - name: Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgeos-dev libproj-dev

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas geopandas folium requests scipy branca matplotlib tqdm shapely aiohttp diskcache

      - name: Run Solar Potential Analysis
        run: |
          python raydium.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Upload Generated Files as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solar-data
          path: |
            india_solar_potential.html
            india_solar_data.csv
            solar_potential_high_res.png

  commit-data:
    name: Commit Generated Data
    runs-on: ubuntu-latest
    needs: generate-data
    steps:
      - name: Checkout Repository (No Git History)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for git operations

      - name: Download Generated Files
        uses: actions/download-artifact@v3
        with:
          name: solar-data
          path: ./generated

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy Generated Files to Repository
        run: |
          cp generated/india_solar_potential.html .
          cp generated/india_solar_data.csv .
          cp generated/solar_potential_high_res.png .

      - name: Commit and Push Changes
        run: |
          git add india_solar_potential.html india_solar_data.csv solar_potential_high_res.png
          git diff --cached --exit-code || git commit -m "Update solar potential data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
