name: Collect and Visualize Solar Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev python3-gdal

      - name: Set environment variables
        run: |
          echo "GDAL_VERSION=$(gdal-config --version)" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          
          # Install GDAL first
          pip install GDAL==$(gdal-config --version)
          
          # Install Fiona explicitly
          pip install fiona==1.9.3
          
          # Install the rest of the requirements
          pip install -r requirements.txt

      # Add debug step
      - name: Debug Python environment
        run: |
          python -c "import fiona; print('Fiona version:', fiona.__version__)"
          python -c "import geopandas; print('GeoPandas version:', geopandas.__version__)"
          python -c "import os; print('GeoJSON exists:', os.path.exists('india-soi.geojson'))"
          ls -la *.geojson

      - name: Run collect_solar_data.py
        run: |
          python collect_solar_data.py

      - name: Commit solar data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add india_solar_data.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update solar data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run visualize_solar_data.py
        run: |
          python visualize_solar_data.py

      - name: Commit visualization files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add solar_potential_high_res.png india_solar_potential.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update solar visualization [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}